In [3]:
import pandas as pdd

In [8]:
data = pd.read_csv("/Users/nivethida/Downloads/accidentsFull.csv")

,HOUR_I_R,ALCHL_I,ALIGN_I,STRATUM_R,WRK_ZONE,WKDY_I_R,INT_HWY,LGTCON_I_R,MANCOL_I_R,PED_ACC_R,...,SUR_COND,TRAF_CON_R,TRAF_WAY,VEH_INVL,WEATHER_R,INJURY_CRASH,NO_INJ_I,PRPTYDMG_CRASH,FATALITIES,MAX_SEV_IR
0,0,2,2,1,0,1,0,3,0,0,...,4,0,3,1,1,1,1,0,0,1
1,1,2,1,0,0,1,1,3,2,0,...,4,0,3,2,2,0,0,1,0,0
2,1,2,1,0,0,1,0,3,2,0,...,4,1,2,2,2,0,0,1,0,0
3,1,2,1,1,0,0,0,3,2,0,...,4,1,2,2,1,0,0,1,0,0
4,1,1,1,0,0,1,0,3,2,0,...,4,0,2,3,1,0,0,1,0,0

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42183 entries, 0 to 42182
Data columns (total 24 columns):
HOUR_I_R          42183 non-null int64
ALCHL_I           42183 non-null int64
ALIGN_I           42183 non-null int64
STRATUM_R         42183 non-null int64
WRK_ZONE          42183 non-null int64
WKDY_I_R          42183 non-null int64
INT_HWY           42183 non-null int64
LGTCON_I_R        42183 non-null int64
MANCOL_I_R        42183 non-null int64
PED_ACC_R         42183 non-null int64
RELJCT_I_R        42183 non-null int64
REL_RWY_R         42183 non-null int64
PROFIL_I_R        42183 non-null int64
SPD_LIM           42183 non-null int64
SUR_COND          42183 non-null int64
TRAF_CON_R        42183 non-null int64
TRAF_WAY          42183 non-null int64
VEH_INVL          42183 non-null int64
WEATHER_R         42183 non-null int64
INJURY_CRASH      42183 non-null int64
NO_INJ_I          42183 non-null int64
PRPTYDMG_CRASH    42183 non-null int64
FATALITIES        42183 non-null int64
MAX_SEV_IR        42183 non-null int64
dtypes: int64(24)
memory usage: 7.7 MB

In [15]:
for x in data.columns:
    print(data.groupby([x]).size())

HOUR_I_R
0    24072
1    18111
dtype: int64
ALCHL_I
1     3677
2    38506
dtype: int64
ALIGN_I
1    36634
2     5549
dtype: int64
STRATUM_R
0    21445
1    20738
dtype: int64
WRK_ZONE
0    41229
1      954
dtype: int64
WKDY_I_R
0     9634
1    32549
dtype: int64
INT_HWY
0    36066
1     6089
9       28
dtype: int64
LGTCON_I_R
1    29294
2     5002
3     7887
dtype: int64
MANCOL_I_R
0    13519
1      926
2    27738
dtype: int64
PED_ACC_R
0    40474
1     1709
dtype: int64
RELJCT_I_R
0    18648
1    23535
dtype: int64
REL_RWY_R
0     9848
1    32335
dtype: int64
PROFIL_I_R
0    31923
1    10260
dtype: int64
SPD_LIM
5        6
10      22
15     183
20     251
25    4205
30    3715
35    8541
40    4304
45    6587
50    1665
55    6594
60    1658
65    2715
70    1454
75     283
dtype: int64
SUR_COND
1    33605
2     6918
3      565
4      909
9      186
dtype: int64
TRAF_CON_R
0    26981
1     8624
2     6578
dtype: int64
TRAF_WAY
1    23993
2    16238
3     1952
dtype: int64
VEH_INVL
1     12800
2     25362
3      3242
4       605
5       126
6        25
7         9
8         9
9         3
10        1
23        1
dtype: int64
WEATHER_R
1    36160
2     6023
dtype: int64
INJURY_CRASH
0    21187
1    20996
dtype: int64
NO_INJ_I
0     20721
1     14225
2      4746
3      1568
4       529
5       233
6        82
7        45
8        17
9         5
10        6
11        3
14        1
20        1
31        1
dtype: int64
PRPTYDMG_CRASH
0    21462
1    20721
dtype: int64
FATALITIES
0    41717
1      466
dtype: int64
MAX_SEV_IR
0    20721
1    20996
2      466
dtype: int64